### ISSUE TITLE
LinkedIn Application has been disabled.

### ISSUE THREAD

**Issue by osatam** [AbdAllahAbdElFattah13/LinkedIn-SDK-Android#15]
![Sign In wirh LinkedIn issue](https://user-images.githubusercontent.com/69801096/136741531-3efcba93-a5b0-43c2-a9c5-412ad23968a3.jpg)

On the click of LinkedIn button this message poped-up

**Comment by AbdAllahAbdElFattah13** [comment]
@osatam 
Can you provide more logs to help find out the exact issue?
